In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

url = 'https://www.icicidirect.com/mailimages/co_reports.htm'
dfs = pd.read_html(url)
#soup = BeautifulSoup(requests.get(urll).text, 'lxml')

In [2]:
# for para in soup.find_all('tbody'):
#     print(para.get_text())

df = dfs[2]

In [3]:
returns = df[4]
df

,0,1,2,3,4,5,6
0,Date,Company,CMP,Target,% Return,NaN,Ratings
1,"Feb 03, 2022",VIP Industries,655,770,17%,Q3FY22 | Q2 | Q1 | Update,Buy
2,"Feb 03, 2022",TTK Prestige,945,1270,35%,Q3FY22 | Update | Q2 | Q1 | Q4,Buy
3,"Feb 03, 2022",Indoco Remedies,398,510,28%,Q3FY22 | Q2 | Q1 | Q4,Buy
4,"Feb 03, 2022",HDFC Ltd,2612,3350,28%,Q3FY22 | Q2 | Q1 | Q4,Buy
...,...,...,...,...,...,...,...
954,"Feb 17, 2016",SH Kelkar & Company,223,-,-,Management Meet,Unrated
955,"Feb 12, 2016",Bank of India,83,-,-,Q3FY16 | Q2 | Q1 | Q4,Dropping Coverage
956,"Feb 08, 2016",Quick Heal Technologies - IPO,311-321,-,-,-,Unrated
957,"Feb 02, 2016",Power Plus,-,-,-,Jan | Dec | Nov | Oct | Sep,-
958,"Jan 25, 2016",Precision Camshaft - IPO,180-186,-,-,-,Avoid

In [6]:
df[3]
z = df.head(100)

In [13]:
del z[5]

In [14]:
z

               0                     1     2       3         4        6
0           Date               Company   CMP  Target  % Return  Ratings
1   Feb 03, 2022        VIP Industries   655     770       17%      Buy
2   Feb 03, 2022          TTK Prestige   945    1270       35%      Buy
3   Feb 03, 2022       Indoco Remedies   398     510       28%      Buy
4   Feb 03, 2022              HDFC Ltd  2612    3350       28%      Buy
..           ...                   ...   ...     ...       ...      ...
95  Jan 22, 2022         Havells India  1242    1515       22%      Buy
96  Jan 21, 2022                Biocon   370     410       11%     Hold
97  Jan 21, 2022            Mastek Ltd  2870    3360       17%      Buy
98  Jan 21, 2022    Hindustan Unilever  2330    2460        6%     Hold
99  Jan 21, 2022  Covid Recovery Pulse     -       -       NaN      NaN

[100 rows x 6 columns]

In [16]:
z.to_excel('updates.xlsx')